# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=99, null=True, verbose_name='文章标题')),
                ('art_content', models.TextField(null=True, verbose_name='文章内容')),
                ('art_tags', models.CharField(max_length=99, null=True, verbose_name='文章标签')),
                ('art_img', models.ImageField(null=True, upload_to='upload', verbose_name='文章图片')),
                ('art_des', models.CharField(max_length=200, null=True, verbose_name='文章描述')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('click_time', models.IntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'db_table': 'user_article',
            },
        ),
    ]
